<a href="https://colab.research.google.com/github/anup-garg/anoop/blob/master/Numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Data Analysis**

In [ ]:
!git clone https://github.com/AshishJangra27/datasets

Cloning into 'datasets'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 328 (delta 19), reused 54 (delta 9), pack-reused 235 (from 1)
Receiving objects: 100% (328/328), 278.62 MiB | 16.88 MiB/s, done.
Resolving deltas: 100% (145/145), done.
Updating files: 100% (225/225), done.


In [ ]:
'/content/datasets/Airbnb/airbnb.csv'

'/content/datasets/Airbnb/airbnb.csv'

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/datasets/Airbnb/airbnb.csv')


In [ ]:
df

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
df.head(5)

id                                               name rating reviews  \
0  49849504                                     Perla bungalov   4.71      64   
1  50891766  Authentic Beach Architect Sheltered Villa with...    New     NaN   
2  50699164                                  cottages sataplia   4.85      68   
3  49871422                        Sapanca Breathable Bungalow    5.0      13   
4  51245886                                      Bungalov Ev 2    New     NaN   

                               host_name      host_id  \
0    Entire bungalow hosted by Mehmetcan  357334205.0   
1           Entire villa hosted by Fatih  386223873.0   
2          Entire cabin hosted by Giorgi  409690853.0   
3        Entire bungalow hosted by Melih  401873242.0   
4  Entire bungalow hosted by Arp Sapanca  414884116.0   

                    address                                features  \
0  Kartepe, Kocaeli, Turkey    2 guests,2 bedrooms,1 bed,1 bathroom   
1      Kaş, Antalya, Turkey  4 guests,2 bedrooms,2 beds,2 bathrooms   
2          Imereti, Georgia    4 guests,1 bedroom,3 beds,1 bathroom   
3  Sapanca, Sakarya, Turkey    4 guests,1 bedroom,2 beds,1 bathroom   
4  Sapanca, Sakarya, Turkey     2 guests,1 bedroom,1 bed,1 bathroom   

                                           amenities  \
0  Mountain view,Valley view,Lake access,Kitchen,...   
1  Kitchen,Wifi,Dedicated workspace,Free parking ...   
2  Mountain view,Kitchen,Wifi,Dedicated workspace...   
3  Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4  Kitchen,Wifi,Free parking on premises,TV,Air c...   

                                        safety_rules  \
0  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   
2  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
3  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
4  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   

                                        hourse_rules  \
0  Check-in: Flexible,Check out: 12:00 pm,Pets ar...   
1  Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...   
2  Check-in: After 1:00 pm,Check out: 12:00 pm,Se...   
3  Check-in: After 2:00 pm,Check out: 12:00 pm,No...   
4  Check-in: After 2:00 pm,Check out: 12:00 pm,No...   

                                           img_links              price  
0  https://a0.muscache.com/im/pictures/a5da5cb7-c...   ₹8,078 per night  
1  https://a0.muscache.com/im/pictures/61b70855-2...   ₹4,665 per night  
2  https://a0.muscache.com/im/pictures/miso/Hosti...   ₹5,991 per night  
3  https://a0.muscache.com/im/pictures/72e6396e-e...  ₹11,339 per night  
4  https://a0.muscache.com/im/pictures/73973308-e...   ₹6,673 per night

In [ ]:
df.tail()

id                                              name rating  \
14451  44697740           Brown Dome House No. 3, full of healing   4.94   
14452  29975283      Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                  Paradise Eco Hub   4.67   
14454   8006146    WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903  Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                             host_name      host_id  \
14451      16                  Dome hosted by Aidan  161552316.0   
14452       6                 Tent hosted by Martha  118954227.0   
14453       3  Private room in dome hosted by Silas  175214568.0   
14454       7                Dome hosted by Cempaka     718423.0   
14455      13                   Dome hosted by Achy  246470880.0   

                                                 address  \
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
14451  󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...   
14452  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   
14453  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
14454  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   
14455  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...   

                                            hourse_rules  \
14451  Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...   
14452  Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...   
14453                            Check-in: After 3:00 pm   
14454  Check-in: Flexible,Check out: 12:00 pm,No pets...   
14455  Check-in: After 4:00 pm,Check out: 11:00 am,Se...   

                                               img_links              price  
14451  https://a0.muscache.com/im/pictures/miso/Hosti...   ₹4,288 per night  
14452  https://a0.muscache.com/im/pictures/5ba944b2-b...  ₹15,200 per night  
14453  https://a0.muscache.com/im/pictures/1f442c84-4...   ₹9,103 per night  
14454  https://a0.muscache.com/im/pictures/105116799/...  ₹42,262 per night  
14455  https://a0.muscache.com/im/pictures/9b04ee4c-c...   ₹9,909 per night

In [ ]:
df.columns

Index(['id', 'name', 'rating', 'reviews', 'host_name', 'host_id', 'address',
       'features', 'amenities', 'safety_rules', 'hourse_rules', 'img_links',
       'price'],
      dtype='object')

In [ ]:
df['id']

0        49849504
1        50891766
2        50699164
3        49871422
4        51245886
           ...   
14451    44697740
14452    29975283
14453    32977697
14454     8006146
14455    40547903
Name: id, Length: 14456, dtype: int64

In [ ]:
df.info()
-

SyntaxError: invalid syntax (<ipython-input-12-3c6000efeb7c>, line 2)

In [ ]:
!git clone /content/datasets/Airbnb/airbnb_v2.csv

In [ ]:
pd2 = pd.read_csv('/content/datasets/Airbnb/airbnb_v2.csv')

In [ ]:
pd2.head()

In [ ]:
del pd2['Unnamed: 0']

In [ ]:
pd2

In [ ]:
pd2['id']

In [ ]:
len(df['id'].unique())

In [ ]:
lst = [1,2,3,4]

In [ ]:
pd.Series(lst)

In [ ]:
step = {'day_1' : 34, 'day_2' : 42, 'day_3' : 47}

In [ ]:
pd.Series(step)

In [ ]:
pd.Series(5).repeat(3)

In [ ]:
pd.Series(5).repeat(3).reset_index(drop=True)

In [ ]:
s = pd.Series([3,2]).repeat([5,1]).reset_index(drop=True)

In [ ]:
s

0    3
1    3
2    3
3    3
4    3
5    2
dtype: int64

In [ ]:
s[0]

np.int64(3)

In [ ]:
s[1:3]

1    3
2    3
dtype: int64

Aggregate function in series

In [ ]:
sr = pd.Series([1,2,3,4,6,5,3,2])

In [ ]:
sr.agg([min,max,sum])

<ipython-input-18-e41e927b3526>:1: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  sr.agg([min,max,sum])
<ipython-input-18-e41e927b3526>:1: FutureWarning: The provided callable <built-in function max> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  sr.agg([min,max,sum])
<ipython-input-18-e41e927b3526>:1: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sr.agg([min,max,sum])


min     1
max     6
sum    26
dtype: int64

In [ ]:
sr.abs()

0    1
1    2
2    3
3    4
4    6
5    5
6    3
7    2
dtype: int64

In [ ]:
sr1 = pd.Series([-1,-2,-3,-4])
sr2 = pd.Series([1,2,3,4])

In [ ]:
result = pd.concat([sr1, sr2])

In [ ]:
result

0   -1
1   -2
2   -3
3   -4
0    1
1    2
2    3
3    4
dtype: int64

Astype functioon used to change the types of series

In [ ]:
sr1

0   -1
1   -2
2   -3
3   -4
dtype: int64

In [ ]:
type(sr1)

pandas.core.series.Series

In [ ]:
sr1.astype('float')

0   -1.0
1   -2.0
2   -3.0
3   -4.0
dtype: float64

Between function to check the value in between 2 argumenr

In [ ]:
sr3 = pd.Series([1,2,3,4,5,6,7,8,9])

In [ ]:
sr3.between(1,6)

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
8    False
dtype: bool

String function

In [ ]:
ser = pd.Series(['anup','arjun','sarthak','karan'])

In [ ]:
ser

0       anup
1      arjun
2    sarthak
3      karan
dtype: object

In [ ]:
ser.str.upper()

0       ANUP
1      ARJUN
2    SARTHAK
3      KARAN
dtype: object

In [ ]:
ser.str.lower()

0       anup
1      arjun
2    sarthak
3      karan
dtype: object

In [ ]:
for i in ser:
  print(len(i))


4
5
7
5


In [ ]:
#Strip for remove extra spaces

In [ ]:
ser.str.strip()

0       anup
1      arjun
2    sarthak
3      karan
dtype: object

In [ ]:
# Split func to split only  the first world of every String

In [ ]:
ser1  = pd.Series(['anup garg','arjun thakur','sarthak krishali','karan Gond'])

In [ ]:
ser1.str.split()
ser1.str.split()[0]

['anup', 'garg']

In [ ]:
#Contain for check series is contain something or not

In [ ]:
ser1.str.contains("a")

0    True
1    True
2    True
3    True
dtype: bool

In [ ]:
#Replace For replace

In [ ]:
ser2 = pd.Series(["Anup@12", "Sarthak12"])

In [ ]:
ser2.str.replace('12',' ')

0      Anup@ 
1    Sarthak 
dtype: object

In [ ]:
#count

In [ ]:
ser1.str.count('a')

0    2
1    2
2    3
3    2
dtype: int64

In [ ]:
#Startwith and endwith

In [ ]:
ser1.str.startswith('a')

0     True
1     True
2    False
3    False
dtype: bool

In [ ]:
ser1.str.endswith('a')

0    False
1    False
2    False
3    False
dtype: bool

In [ ]:
ser1.str.find('anup')

0    0
1   -1
2   -1
3   -1
dtype: int64

In [ ]:
ser1

0           anup garg
1        arjun thakur
2    sarthak krishali
3          karan Gond
dtype: object

In [ ]:
#Convert series into lst

In [ ]:
ser1.to_list()

['anup garg', 'arjun thakur', 'sarthak krishali', 'karan Gond']

## **DataFrame**

In [ ]:
#DataFrame consists of three principal 1. components,2. rows 3. columns

In [ ]:
lst = [1,2,4,5,6,7,8,9,0,-7]

In [ ]:
pd.DataFrame(lst)

0
0  1
1  2
2  4
3  5
4  6
5  7
6  8
7  9
8  0
9 -7

In [ ]:
lst = [['anup','garg'],['sarthak','Krishali'],['karan','Gond']]

In [ ]:
pd.DataFrame(lst)

0         1
0     anup      garg
1  sarthak  Krishali
2    karan      Gond

In [ ]:
Dic = {'Name':['anup','sarthak','karan'],'Surname':['garg','krishali','gond']}

In [ ]:
pd.DataFrame(Dic)

Name   Surname
0     anup      garg
1  sarthak  krishali
2    karan      gond

# DataFrame  we can perform basic operatin like selecting adding and deleting  renaming rows and **column** **bold text**

In [ ]:
data = {'name': ['anup','sarthak','arjun','karan'],
        'lastName': ['Garg','krishali','thakur','gond'],
        'Address': ['Raj','uk','UP','UP']}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

name  lastName Address
0     anup      Garg     Raj
1  sarthak  krishali      uk
2    arjun    thakur      UP
3    karan      gond      UP

In [ ]:
df[['name']]

name
0     anup
1  sarthak
2    arjun
3    karan

In [ ]:
df


name  lastName Address
0     anup      Garg     Raj
1  sarthak  krishali      uk
2    arjun    thakur      UP
3    karan      gond      UP

In [ ]:
df.loc[1:2,'name':'address']

name  lastName
1  sarthak  krishali
2    arjun    thakur

In [ ]:
#iloc is totally index based

In [ ]:
df

name  lastName Address
0     anup      Garg     Raj
1  sarthak  krishali      uk
2    arjun    thakur      UP
3    karan      gond      UP

In [ ]:
df.iloc[[1,3],[1,2]]

lastName Address
1  krishali      uk
3      gond      UP

In [ ]:
df['name'] == 'anup'

0     True
1    False
2    False
3    False
Name: name, dtype: bool

In [ ]:
df.loc[df['name'] == 'anup','name']


0    anup
Name: name, dtype: object

In [ ]:
df

name  lastName Address
0  anup      Garg     Raj
1  anup  krishali      uk
2  anup    thakur      UP
3  anup      gond      UP

In [ ]:
# Add column in dataframe

In [ ]:
l = [22,23,24,25]

In [ ]:
df['age'] = l

In [ ]:
df

name  lastName Address  age
0     anup      Garg     Raj   22
1  sarthak  krishali      uk   23
2    arjun    thakur      UP   24
3    karan      gond      UP   25

In [ ]:
# Using a exising column

In [ ]:
data

{'name': ['anup', 'sarthak', 'arjun', 'karan'],
 'lastName': ['Garg', 'krishali', 'thakur', 'gond'],
 'Address': ['Raj', 'uk', 'UP', 'UP']}

In [ ]:
df


0                    25
1                    26
2                    27
3                    28
age    [22, 23, 24, 25]
Name: age, dtype: object

In [ ]:
data = pd.DataFrame(data)

In [ ]:
data

name  lastName Address
0     anup      Garg     Raj
1  sarthak  krishali      uk
2    arjun    thakur      UP
3    karan      gond      UP

In [ ]:
df

name  lastName Address  age
0     anup      Garg     Raj   22
1  sarthak  krishali      uk   23
2    arjun    thakur      UP   24
3    karan      gond      UP   25

In [ ]:
df['dou_age'] = df['age'] + 10

In [ ]:
df

name  lastName Address  age  dou_age
0     anup      Garg     Raj   22       32
1  sarthak  krishali      uk   23       33
2    arjun    thakur      UP   24       34
3    karan      gond      UP   25       35

In [ ]:
#Delete a column

In [ ]:
del df['dou_age']
df

name  lastName Address  age
0     anup      Garg     Raj   22
1  sarthak  krishali      uk   23
2    arjun    thakur      UP   24
3    karan      gond      UP   25

In [ ]:
df.pop('age')

0    22
1    23
2    24
3    25
Name: age, dtype: int64

In [ ]:
df

name  lastName Address
0     anup      Garg     Raj
1  sarthak  krishali      uk
2    arjun    thakur      UP
3    karan      gond      UP

In [ ]:
#Adding of rows

In [ ]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]], columns=['a','b','c'])
df2 = pd.DataFrame([[7,8,9],[10,11,12]], columns=['a','b','c'])

In [ ]:
df3 = pd.concat([df1,df2]).reset_index(drop=True)

In [ ]:
df3

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [ ]:
#Drop function

In [ ]:
  df

name  lastName Address
0     anup      Garg     Raj
1  sarthak  krishali      uk
2    arjun    thakur      UP
3    karan      gond      UP

In [ ]:
df.drop([0,1], axis = 0)

KeyError: '[0, 1] not found in axis'

In [ ]:
df3

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [ ]:
# tranforming data

In [ ]:
df3.T

0  1  2   3
a  1  4  7  10
b  2  5  8  11
c  3  6  9  12

In [ ]:
df3.axes

[RangeIndex(start=0, stop=4, step=1), Index(['a', 'b', 'c'], dtype='object')]

In [ ]:
df.ndim

2

In [ ]:
'/content/datasets/Airbnb/airbnb.csv'

'/content/datasets/Airbnb/airbnb.csv'

In [ ]:
df = pd.read_csv('/content/datasets/Airbnb/airbnb.csv')

In [ ]:
df

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
df.head(5)

id                                               name rating reviews  \
0  49849504                                     Perla bungalov   4.71      64   
1  50891766  Authentic Beach Architect Sheltered Villa with...    New     NaN   
2  50699164                                  cottages sataplia   4.85      68   
3  49871422                        Sapanca Breathable Bungalow    5.0      13   
4  51245886                                      Bungalov Ev 2    New     NaN   

                               host_name      host_id  \
0    Entire bungalow hosted by Mehmetcan  357334205.0   
1           Entire villa hosted by Fatih  386223873.0   
2          Entire cabin hosted by Giorgi  409690853.0   
3        Entire bungalow hosted by Melih  401873242.0   
4  Entire bungalow hosted by Arp Sapanca  414884116.0   

                    address                                features  \
0  Kartepe, Kocaeli, Turkey    2 guests,2 bedrooms,1 bed,1 bathroom   
1      Kaş, Antalya, Turkey  4 guests,2 bedrooms,2 beds,2 bathrooms   
2          Imereti, Georgia    4 guests,1 bedroom,3 beds,1 bathroom   
3  Sapanca, Sakarya, Turkey    4 guests,1 bedroom,2 beds,1 bathroom   
4  Sapanca, Sakarya, Turkey     2 guests,1 bedroom,1 bed,1 bathroom   

                                           amenities  \
0  Mountain view,Valley view,Lake access,Kitchen,...   
1  Kitchen,Wifi,Dedicated workspace,Free parking ...   
2  Mountain view,Kitchen,Wifi,Dedicated workspace...   
3  Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4  Kitchen,Wifi,Free parking on premises,TV,Air c...   

                                        safety_rules  \
0  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   
2  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
3  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
4  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   

                                        hourse_rules  \
0  Check-in: Flexible,Check out: 12:00 pm,Pets ar...   
1  Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...   
2  Check-in: After 1:00 pm,Check out: 12:00 pm,Se...   
3  Check-in: After 2:00 pm,Check out: 12:00 pm,No...   
4  Check-in: After 2:00 pm,Check out: 12:00 pm,No...   

                                           img_links              price  
0  https://a0.muscache.com/im/pictures/a5da5cb7-c...   ₹8,078 per night  
1  https://a0.muscache.com/im/pictures/61b70855-2...   ₹4,665 per night  
2  https://a0.muscache.com/im/pictures/miso/Hosti...   ₹5,991 per night  
3  https://a0.muscache.com/im/pictures/72e6396e-e...  ₹11,339 per night  
4  https://a0.muscache.com/im/pictures/73973308-e...   ₹6,673 per night

In [ ]:
df.tail()

id                                              name rating  \
14451  44697740           Brown Dome House No. 3, full of healing   4.94   
14452  29975283      Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                  Paradise Eco Hub   4.67   
14454   8006146    WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903  Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                             host_name      host_id  \
14451      16                  Dome hosted by Aidan  161552316.0   
14452       6                 Tent hosted by Martha  118954227.0   
14453       3  Private room in dome hosted by Silas  175214568.0   
14454       7                Dome hosted by Cempaka     718423.0   
14455      13                   Dome hosted by Achy  246470880.0   

                                                 address  \
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
14451  󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...   
14452  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   
14453  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
14454  󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...   
14455  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...   

                                            hourse_rules  \
14451  Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...   
14452  Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...   
14453                            Check-in: After 3:00 pm   
14454  Check-in: Flexible,Check out: 12:00 pm,No pets...   
14455  Check-in: After 4:00 pm,Check out: 11:00 am,Se...   

                                               img_links              price  
14451  https://a0.muscache.com/im/pictures/miso/Hosti...   ₹4,288 per night  
14452  https://a0.muscache.com/im/pictures/5ba944b2-b...  ₹15,200 per night  
14453  https://a0.muscache.com/im/pictures/1f442c84-4...   ₹9,103 per night  
14454  https://a0.muscache.com/im/pictures/105116799/...  ₹42,262 per night  
14455  https://a0.muscache.com/im/pictures/9b04ee4c-c...   ₹9,909 per night

In [ ]:
df

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
df.head(1)

id            name rating reviews  \
0  49849504  Perla bungalov   4.71      64   

                             host_name      host_id                   address  \
0  Entire bungalow hosted by Mehmetcan  357334205.0  Kartepe, Kocaeli, Turkey   

                               features  \
0  2 guests,2 bedrooms,1 bed,1 bathroom   

                                           amenities  \
0  Mountain view,Valley view,Lake access,Kitchen,...   

                                        safety_rules  \
0  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   

                                        hourse_rules  \
0  Check-in: Flexible,Check out: 12:00 pm,Pets ar...   

                                           img_links             price  
0  https://a0.muscache.com/im/pictures/a5da5cb7-c...  ₹8,078 per night

In [ ]:
df.sum()

TypeError: can only concatenate str (not "int") to str

In [ ]:
df.head(1)

id            name rating reviews  \
0  49849504  Perla bungalov   4.71      64   

                             host_name      host_id                   address  \
0  Entire bungalow hosted by Mehmetcan  357334205.0  Kartepe, Kocaeli, Turkey   

                               features  \
0  2 guests,2 bedrooms,1 bed,1 bathroom   

                                           amenities  \
0  Mountain view,Valley view,Lake access,Kitchen,...   

                                        safety_rules  \
0  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   

                                        hourse_rules  \
0  Check-in: Flexible,Check out: 12:00 pm,Pets ar...   

                                           img_links             price  
0  https://a0.muscache.com/im/pictures/a5da5cb7-c...  ₹8,078 per night

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14456 entries, 0 to 14455
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            14456 non-null  int64  
 1   name          14455 non-null  object 
 2   rating        14456 non-null  object 
 3   reviews       11712 non-null  object 
 4   host_name     14455 non-null  object 
 5   host_id       14017 non-null  float64
 6   address       14429 non-null  object 
 7   features      14429 non-null  object 
 8   amenities     13467 non-null  object 
 9   safety_rules  14247 non-null  object 
 10  hourse_rules  14247 non-null  object 
 11  img_links     14429 non-null  object 
 12  price         14456 non-null  object 
dtypes: float64(1), int64(1), object(11)
memory usage: 1.4+ MB


In [ ]:
df['id'].sum()

np.int64(-1115554469511385024)

In [ ]:
df['id'].mean()

np.float64(7.138227128238956e+16)

In [ ]:
df['id'].median()

35243202.5

In [ ]:
de = pd.DataFrame({'A':[1,2,3,4,5,6,7,8,9,10],'B' : [11,12,13,14,15,16,17,18,19,20]})

In [ ]:
de['A']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: A, dtype: int64

In [ ]:
print('A', de['A'].mode())

A 0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: A, dtype: int64


In [ ]:
de['A'].mode()

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: A, dtype: int64

In [ ]:
de.var()

A    9.166667
B    9.166667
dtype: float64

In [ ]:
 de.min()

A     1
B    11
dtype: int64

In [ ]:
 df3

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [ ]:
da = pd.DataFrame(df3)

In [ ]:
da

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [ ]:
da.describe()

a          b          c
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [ ]:
#PIP function

In [ ]:
df3

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [ ]:
def add_(i,j):
  return i + j

In [ ]:
df3.pipe(add_,20)

a   b   c
0  21  22  23
1  24  25  26
2  27  28  29
3  30  31  32

In [ ]:
df3.mean()

a    5.5
b    6.5
c    7.5
dtype: float64

In [ ]:
import numpy as np

In [ ]:
df3.apply(np.mean)

a    5.5
b    6.5
c    7.5
dtype: float64

In [ ]:
#Apply Map

In [ ]:
df3.applymap(np.int64)

<ipython-input-36-cabbe64f2570>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df3.applymap(np.int64)


a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [ ]:
#Reindex function

In [ ]:
df

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
df.head(1)

id            name rating reviews  \
0  49849504  Perla bungalov   4.71      64   

                             host_name      host_id                   address  \
0  Entire bungalow hosted by Mehmetcan  357334205.0  Kartepe, Kocaeli, Turkey   

                               features  \
0  2 guests,2 bedrooms,1 bed,1 bathroom   

                                           amenities  \
0  Mountain view,Valley view,Lake access,Kitchen,...   

                                        safety_rules  \
0  󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   

                                        hourse_rules  \
0  Check-in: Flexible,Check out: 12:00 pm,Pets ar...   

                                           img_links             price  
0  https://a0.muscache.com/im/pictures/a5da5cb7-c...  ₹8,078 per night

In [ ]:
df3

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12

In [ ]:
df3.reindex([3,2,1,0])

a   b   c
3  10  11  12
2   7   8   9
1   4   5   6
0   1   2   3

In [ ]:
df3.rename(index = {0 : 'A', 1 : 'B', 2 : 'C', 3 : 'D'}, inplace = True)

In [ ]:
df3

a   b   c
A   1   2   3
B   4   5   6
C   7   8   9
D  10  11  12

In [ ]:
#Sort function

In [ ]:
df3.sort_values(by = 'a', ascending=False)

a   b   c
D  10  11  12
C   7   8   9
B   4   5   6
A   1   2   3

In [ ]:
#Based on multiple column

In [ ]:
df3.sort_values(by = ['a','c'], ascending=False)

a   b   c
D  10  11  12
C   7   8   9
B   4   5   6
A   1   2   3

In [ ]:
student_data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Helen", "Ian", "Judy"],
    "Roll Number": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Marks": [85, 90, 78, 88, 92, 75, 89, 84, 91, 87],
    "Grade": ['B', 'A', 'C', 'B', 'A', 'C', 'B', 'B', 'A', 'B'],
    "Passed": [True, True, True, True, True, True, True, True, True, True]
}

# Create a DataFrame
df4 = pd.DataFrame(student_data)

# Display the DataFrame
print(df4)

      Name  Roll Number  Marks Grade  Passed
0    Alice          101     85     B    True
1      Bob          102     90     A    True
2  Charlie          103     78     C    True
3    David          104     88     B    True
4      Eve          105     92     A    True
5    Frank          106     75     C    True
6    Grace          107     89     B    True
7    Helen          108     84     B    True
8      Ian          109     91     A    True
9     Judy          110     87     B    True


In [ ]:
df4.groupby('Grade').groups

{'A': [1, 4, 8], 'B': [0, 3, 6, 7, 9], 'C': [2, 5]}

In [ ]:
df4.groupby('Grade').get_group(('B'))

Name  Roll Number  Marks Grade  Passed
0  Alice          101     85     B    True
3  David          104     88     B    True
6  Grace          107     89     B    True
7  Helen          108     84     B    True
9   Judy          110     87     B    True

In [ ]:
df4.groupby('Name')['Marks'].sum()

Name
Alice      85
Bob        90
Charlie    78
David      88
Eve        92
Frank      75
Grace      89
Helen      84
Ian        91
Judy       87
Name: Marks, dtype: int64

In [ ]:
df4.groupby('Name')['Marks'].sum().sort_values(ascending=False)

Name
Eve        92
Ian        91
Bob        90
Grace      89
David      88
Judy       87
Alice      85
Helen      84
Charlie    78
Frank      75
Name: Marks, dtype: int64

In [ ]:
#apply agg() function

In [ ]:
groups = df4.groupby('Name')
groups['Marks'].agg([np.min,np.max,np.mean,np.std])

<ipython-input-63-3a7f3f363e95>:2: FutureWarning: The provided callable <function min at 0x7be010109760> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  groups['Marks'].agg([np.min,np.max,np.mean,np.std])
<ipython-input-63-3a7f3f363e95>:2: FutureWarning: The provided callable <function max at 0x7be010109620> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  groups['Marks'].agg([np.min,np.max,np.mean,np.std])
<ipython-input-63-3a7f3f363e95>:2: FutureWarning: The provided callable <function mean at 0x7be01010a020> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  groups['Marks'].agg([np.min,np.max,np.mean,np.std])
<ipython-i

min  max  mean  std
Name                        
Alice     85   85  85.0  NaN
Bob       90   90  90.0  NaN
Charlie   78   78  78.0  NaN
David     88   88  88.0  NaN
Eve       92   92  92.0  NaN
Frank     75   75  75.0  NaN
Grace     89   89  89.0  NaN
Helen     84   84  84.0  NaN
Ian       91   91  91.0  NaN
Judy      87   87  87.0  NaN

In [ ]:
df

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
df.isnull()

id   name  rating  reviews  host_name  host_id  address  features  \
0      False  False   False    False      False    False    False     False   
1      False  False   False     True      False    False    False     False   
2      False  False   False    False      False    False    False     False   
3      False  False   False    False      False    False    False     False   
4      False  False   False     True      False    False    False     False   
...      ...    ...     ...      ...        ...      ...      ...       ...   
14451  False  False   False    False      False    False    False     False   
14452  False  False   False    False      False    False    False     False   
14453  False  False   False    False      False    False    False     False   
14454  False  False   False    False      False    False    False     False   
14455  False  False   False    False      False    False    False     False   

       amenities  safety_rules  hourse_rules  img_links  price  
0          False         False         False      False  False  
1          False         False         False      False  False  
2          False         False         False      False  False  
3          False         False         False      False  False  
4          False         False         False      False  False  
...          ...           ...           ...        ...    ...  
14451      False         False         False      False  False  
14452      False         False         False      False  False  
14453      False         False         False      False  False  
14454      False         False         False      False  False  
14455      False         False         False      False  False  

[14456 rows x 13 columns]

In [ ]:
df.isnull().sum()

id                 0
name               1
rating             0
reviews         2744
host_name          1
host_id          439
address           27
features          27
amenities        989
safety_rules     209
hourse_rules     209
img_links         27
price              0
dtype: int64

In [ ]:
df.describe(percentiles = [.80])

id       host_id
count  1.445600e+04  1.401700e+04
mean   7.138227e+16  1.619384e+08
std    1.962072e+17  1.403407e+08
min    1.313100e+04  2.303900e+04
50%    3.524320e+07  1.243490e+08
80%    5.133860e+07  3.053249e+08
max    7.017905e+17  4.758973e+08

In [ ]:
df

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
dg = df.copy()

In [ ]:
dg

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
#Dropna() for drop null vales

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

id              0
name            0
rating          0
reviews         0
host_name       0
host_id         0
address         0
features        0
amenities       0
safety_rules    0
hourse_rules    0
img_links       0
price           0
dtype: int64

In [ ]:
df.isnull().sum()

id              0
name            0
rating          0
reviews         0
host_name       0
host_id         0
address         0
features        0
amenities       0
safety_rules    0
hourse_rules    0
img_links       0
price           0
dtype: int64

In [ ]:
df3

a   b   c
A   1   2   3
B   4   5   6
C   7   8   9
D  10  11  12

In [ ]:
df3['d'] = [1,2,4,'']

In [ ]:
df3

a   b   c  d
A   1   2   3  1
B   4   5   6  2
C   7   8   9  4
D  10  11  12

In [ ]:
#fillnull value for fill the null values with like mean or sum and average and other things

In [ ]:
de

A   B
0   1  11
1   2  12
2   3  13
3   4  14
4   5  15
5   6  16
6   7  17
7   8  18
8   9  19
9  10  20

In [ ]:
dg

id                                               name rating  \
0      49849504                                     Perla bungalov   4.71   
1      50891766  Authentic Beach Architect Sheltered Villa with...    New   
2      50699164                                  cottages sataplia   4.85   
3      49871422                        Sapanca Breathable Bungalow    5.0   
4      51245886                                      Bungalov Ev 2    New   
...         ...                                                ...    ...   
14451  44697740            Brown Dome House No. 3, full of healing   4.94   
14452  29975283       Bubble Hotel Ubud with Bathtub under the Sky   4.67   
14453  32977697                                   Paradise Eco Hub   4.67   
14454   8006146     WisDOME - Mentigi Bay Village - Gilis - Lombok   4.86   
14455  40547903   Enjoy Vitamin SEA!  Ocean Front! [Ocean's Seven]   4.85   

      reviews                              host_name      host_id  \
0          64    Entire bungalow hosted by Mehmetcan  357334205.0   
1         NaN           Entire villa hosted by Fatih  386223873.0   
2          68          Entire cabin hosted by Giorgi  409690853.0   
3          13        Entire bungalow hosted by Melih  401873242.0   
4         NaN  Entire bungalow hosted by Arp Sapanca  414884116.0   
...       ...                                    ...          ...   
14451      16                   Dome hosted by Aidan  161552316.0   
14452       6                  Tent hosted by Martha  118954227.0   
14453       3   Private room in dome hosted by Silas  175214568.0   
14454       7                 Dome hosted by Cempaka     718423.0   
14455      13                    Dome hosted by Achy  246470880.0   

                                                 address  \
0                               Kartepe, Kocaeli, Turkey   
1                                   Kaş, Antalya, Turkey   
2                                       Imereti, Georgia   
3                               Sapanca, Sakarya, Turkey   
4                               Sapanca, Sakarya, Turkey   
...                                                  ...   
14451  Imhoe-myeon, Jindo, South Jeolla Province, Sou...   
14452                                 Gianyar, Indonesia   
14453                                     Kabale, Uganda   
14454        Gunung Sari, Nusa Tenggara Barat, Indonesia   
14455                              Uruma, Okinawa, Japan   

                                           features  \
0              2 guests,2 bedrooms,1 bed,1 bathroom   
1            4 guests,2 bedrooms,2 beds,2 bathrooms   
2              4 guests,1 bedroom,3 beds,1 bathroom   
3              4 guests,1 bedroom,2 beds,1 bathroom   
4               2 guests,1 bedroom,1 bed,1 bathroom   
...                                             ...   
14451                          4 guests,8 bathrooms   
14452     2 guests,1 bedroom,1 bed,Toilet with sink   
14453  2 guests,1 bedroom,2 beds,1 private bathroom   
14454      8 guests,2 bedrooms,4 beds,2.5 bathrooms   
14455          5 guests,1 bedroom,2 beds,1 bathroom   

                                               amenities  \
0      Mountain view,Valley view,Lake access,Kitchen,...   
1      Kitchen,Wifi,Dedicated workspace,Free parking ...   
2      Mountain view,Kitchen,Wifi,Dedicated workspace...   
3      Mountain view,Valley view,Kitchen,Wifi,Free pa...   
4      Kitchen,Wifi,Free parking on premises,TV,Air c...   
...                                                  ...   
14451  Kitchen,Wifi,Free parking on premises,Private ...   
14452  Wifi,Free on-street parking,Air conditioning,G...   
14453  Wifi,Breakfast,Long-term stays allowed,Unavail...   
14454  Kitchen,Wifi,Dedicated workspace,Free parking ...   
14455  Sea view,Beach access – Beachfront,Kitchen,Wif...   

                                            safety_rules  \
0      󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...   
1      󹀁,Airbnb's COVID-19 safety pr

In [ ]:
import pandas_profiling as pp

ModuleNotFoundError: No module named 'pandas_profiling'

In [ ]:
!pip install pandas-profiling[notebook]
import pandas_profiling as pp

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 36.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.4/102.4 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.8/309.8 kB 21.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.8/687.8 kB 34.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 262.6/262.6 kB 19.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 22.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 53.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 47.4 MB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=7886275278778c7190c64c2c83df388b084f382c3415be2eeb7c30399fda82cf
  Stored in directory: /root/.cache/pip/wheels/8d/55/1a/19cd535375ed1ede0c996405ebffe34b196d78e2d9545723a2
Successfully built htmlmin
  Attempting uninstall: markupsafe
  

AttributeError: module 'numba' has no attribute 'generated_jit'

# **Numpy**

In [ ]:
 import numpy as np

In [ ]:
#1. Converting list into array

In [ ]:
lst = [1,2,3,4]

In [ ]:
arr = np.array(lst)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:

arr = np.array(lst,ndmin = 2)

In [ ]:


arr

array([[1, 2, 3, 4]])

In [ ]:
# 2. Arrange

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
# 3.  multideminsational

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# size

In [ ]:
arr.size

9

In [ ]:
print("Rows",np.size(arr,0))
print("Column",np.size(arr,1))

Rows 3
Column 3


In [ ]:

arr.shape

(3, 3)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
print(arr.ndim)

2


In [ ]:
# Eye function

In [ ]:
np.eye(20)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [ ]:
#Empty function

In [ ]:
np.empty(shape = (3,3))

array([[3.10380503e-315, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [ ]:
#random functin

In [ ]:
np.random.rand(3,3)

array([[0.47043806, 0.68747863, 0.7910497 ],
       [0.32599236, 0.32108237, 0.74435846],
       [0.58860948, 0.00766584, 0.87989422]])

In [ ]:
np.random.randint(low = 1,high = 10,size = (3,3))

array([[9, 3, 7],
       [9, 5, 2],
       [2, 6, 7]])

In [ ]:
np.random.randn(40)

array([ 2.33135559, -1.94319694, -0.25686159, -0.17672072,  0.33320873,
        1.01055442,  0.03255481, -0.12236344, -1.60689452,  0.07357892,
        1.18948933,  0.63491166, -0.16980963, -0.24264369,  0.54523081,
        0.90520793,  0.66643162, -0.68009881, -0.94409788, -0.73810448,
        0.14211237,  0.09983064, -0.01746854,  0.48854827, -0.41027632,
        0.29778965,  1.00470522, -0.36816279,  1.64946687,  0.2611022 ,
       -2.36624498,  0.93733294,  1.65271105,  0.8563478 , -0.74501633,
        0.49593274, -0.38657869, -0.55210692,  1.13288832, -1.45586791])

In [ ]:
#Reshape function :

In [ ]:
arr = np.random.randint(1,15,(3,4))

In [ ]:
print(arr)

[[ 6  8  4 10]
 [13 10 12 13]
 [12 10  8  6]]


In [ ]:
arr.reshape(4,3)

array([[ 6,  8,  4],
       [10, 13, 10],
       [12, 13, 12],
       [10,  8,  6]])

In [ ]:
#lineshape

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#flatten function

In [ ]:
arr = np.random.randint(1,15,(3,4))
arr = arr.flatten()
arr

array([ 1,  4, 13,  9,  6,  4, 13,  8,  2, 11, 10, 10])

In [ ]:
#logspace :

In [ ]:
print(np.logspace(1,10,5))

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [ ]:
#copy function

In [ ]:
arr1 = np.random.randint(1,10,5)

In [ ]:
arr1

array([1, 2, 3, 5, 6])

In [ ]:
arr2 = np.copy(arr1)

In [ ]:
arr2

array([1, 2, 3, 5, 6])

In [ ]:
#Arr max , min  , sum

In [ ]:
arr = np.random.randint(1,10,(4,4))

In [ ]:
arr

array([[1, 7, 5, 4],
       [2, 6, 1, 8],
       [7, 6, 7, 1],
       [1, 6, 2, 4]])

In [ ]:
arr.max()


np.int64(8)

In [ ]:
arr.min()


np.int64(1)

In [ ]:
arr.sum()

np.int64(68)

In [ ]:
arr.max(axis = 0)


array([7, 7, 7, 8])

In [ ]:
# seed function

In [ ]:
# Syntax : random.seed( i, version )<br>


In [ ]:
np.random.seed(3)
arr = np.random.randint(1,10,(4,4))
arr

array([[9, 4, 9, 9],
       [1, 6, 4, 6],
       [8, 7, 1, 5],
       [8, 9, 2, 7]])

In [ ]:
arr = np.random.randint(1,10,(4,4))
arr

array([[5, 8, 7, 1],
       [1, 3, 5, 6],
       [9, 9, 8, 6],
       [2, 2, 2, 6]])

In [ ]:
# sorting function

In [ ]:
np.random.seed(3)
arr = np.random.randint(1,10,(4,4))
print(arr)
print('*'*20)

print(np.sort(arr,axis = 0))

[[9 4 9 9]
 [1 6 4 6]
 [8 7 1 5]
 [8 9 2 7]]
********************
[[1 4 1 5]
 [8 6 2 6]
 [8 7 4 7]
 [9 9 9 9]]


In [ ]:
# mathemecical Operation

In [ ]:
np.random.seed(3)
arr = np.random.randint(1,10,(4,4))
print(arr)
print('*'*20)

print(arr+1)
print('*'*20)
print(arr-1)
print('*'*20)
print(arr*2)
print('*'*20)
print(arr/2)
print('*'*20)
print(arr%2)
print('*'*20)

[[9 4 9 9]
 [1 6 4 6]
 [8 7 1 5]
 [8 9 2 7]]
********************
[[10  5 10 10]
 [ 2  7  5  7]
 [ 9  8  2  6]
 [ 9 10  3  8]]
********************
[[8 3 8 8]
 [0 5 3 5]
 [7 6 0 4]
 [7 8 1 6]]
********************
[[18  8 18 18]
 [ 2 12  8 12]
 [16 14  2 10]
 [16 18  4 14]]
********************
[[4.5 2.  4.5 4.5]
 [0.5 3.  2.  3. ]
 [4.  3.5 0.5 2.5]
 [4.  4.5 1.  3.5]]
********************
[[1 0 1 1]
 [1 0 0 0]
 [0 1 1 1]
 [0 1 0 1]]
********************


In [ ]:
# matrix maltiplication

In [ ]:
np.random.seed(3)
arr1 = np.random.randint(1,10,(4,4))
print(arr1)
arr2 = np.random.randint(1,10,(4,4))
print('*'*20)
print(arr2)
print('*'*20)
print(np.dot(arr1,arr2))

[[9 4 9 9]
 [1 6 4 6]
 [8 7 1 5]
 [8 9 2 7]]
********************
[[3 3 2 4]
 [6 9 2 9]
 [8 9 2 1]
 [6 5 2 6]]
********************
[[177 189  62 135]
 [107 123  34  98]
 [104 121  42 126]
 [136 158  52 157]]


In [ ]:
# percentage function

In [ ]:
np.random.seed(3)
arr = np.random.randint(1,10,10)
print(arr)
print('*'*20)
print(np.percentile(arr,50))

[9 4 9 9 1 6 4 6 8 7]
********************
6.5


In [ ]:
 # filter

In [ ]:
arr = np.random.randint(1,10,10)
print(arr)
print(arr<5)
print(arr[arr<5])

[9 9 8 6 2 2 2 6 6 8]
[False False False False  True  True  True False False False]
[2 2 2]


In [ ]:
where clause